// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohcodfqxrgihpixnapza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oY29kZnF4cmdpaHBpeG5hcHphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzg0OTQsImV4cCI6MjA2NjgxNDQ5NH0.S7LXMVF9yz3AXrCtS_6Pkk9Rdg2c_VtkYH3WKJMJAYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});